name: .NET Core

on:
  push:  
    branches: [ beta, v1 ]

  pull_request:
    branches: [ beta, v1 ]

jobs:
   build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.3
    
    - name: Build Project
      run: dotnet build /p:Version=0.0.{{ github.run_number }} --configuration Release -o Output

    - name: Myget Upload
      if: success()
      working-directory: Output
      run: dotnet nuget push *.nupkg -k ${{ secrets.MYGET_KEY }} -s https://www.myget.org/F/yucked/api/v3/index.json --skip-duplicate
    
    - name: Discord WebHook
      if: always()
      shell: pwsh
      env: 
        GITHUB: ${{ toJson(github) }} 
      run: |
        wget https://raw.githubusercontent.com/Yucked/Scripy/master/Powershell/ActionSend.ps1
        pwsh .\ActionSend.ps1 ${{ secrets.WEBHOOK }} ${{ job.status }}
